### PR TITLE
iss1 - add bio

### PR DESCRIPTION
**Pull request by JustineD56**
Just add bio with my picture

### CODE REVIEW

**Review by JustineD56 — COMMENTED** [review]
Request review changes bio @me-pic

**Review by JustineD56 — COMMENTED** [review]
Sorry... this is my bio with my picture @me-pic

**Review by me-pic — CHANGES_REQUESTED** [review]
Can you please add a few lines about your background and general interests ?

**Review by JustineD56 — COMMENTED** [review]
Add few more lines @me-pic

**Review by me-pic — APPROVED** [review]
LGTM !

**Pull request merged**
